[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; img-src 'self' data: blob: *.netlify.app; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "https://3mmar1.netlify.app/*"
  to = "https://3mmar.info/:splat"
  status = 301
  force = true
  conditions = {Host = "3mmar1.netlify.app"}